/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "surface": "#16111b",
        "surface-dim": "#16111b",
        "surface-bright": "#3d3741",
        "surface-container-lowest": "#110c15",
        "surface-container-low": "#1f1a23",
        "surface-container": "#231e27",
        "surface-container-high": "#2e2832",
        "surface-container-highest": "#39323d",
        "on-surface": "#eadfed",
        "on-surface-variant": "#cfc2d6",
        "inverse-surface": "#eadfed",
        "inverse-on-surface": "#342e38",
        "outline": "#988d9f",
        "outline-variant": "#4d4354",
        "surface-tint": "#ddb7ff",
        "primary": "#ddb7ff",
        "on-primary": "#490080",
        "primary-container": "#b76dff",
        "on-primary-container": "#400071",
        "inverse-primary": "#842bd2",
        "secondary": "#fbabff",
        "on-secondary": "#580065",
        "secondary-container": "#ae05c6",
        "on-secondary-container": "#ffd8fd",
        "tertiary": "#fabc4e",
        "on-tertiary": "#432c00",
        "tertiary-container": "#bd871a",
        "on-tertiary-container": "#3a2600",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#f0dbff",
        "primary-fixed-dim": "#ddb7ff",
        "on-primary-fixed": "#2c0051",
        "on-primary-fixed-variant": "#6900b3",
        "secondary-fixed": "#ffd6fd",
        "secondary-fixed-dim": "#fbabff",
        "on-secondary-fixed": "#36003e",
        "on-secondary-fixed-variant": "#7c008e",
        "tertiary-fixed": "#ffdead",
        "tertiary-fixed-dim": "#fabc4e",
        "on-tertiary-fixed": "#281900",
        "on-tertiary-fixed-variant": "#604100",
        "background": "#16111b",
        "on-background": "#eadfed",
        "surface-variant": "#39323d"
      },
      fontFamily: {
        "h1": ["Inter", "sans-serif"],
        "h2": ["Inter", "sans-serif"],
        "h3": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "code": ["Inter", "monospace"]
      }
    },
  },
  plugins: [],
}
